export interface ExamplePreset {
  file: string;
  label: string;
}

export const EXAMPLE_PRESETS: ExamplePreset[] = [
  { file: '01-parametric-extrude.json', label: '示例1 参数化拉伸' },
  { file: '02-boolean-cut.json', label: '示例2 布尔切割' },
  { file: '03-data-array.json', label: '示例3 数据驱动阵列' },
  { file: '04-revolve-form.json', label: '示例4 旋转成形' },
  { file: '05-sweep-path.json', label: '示例5 路径扫掠' },
  { file: '06-loft-sections.json', label: '示例6 截面放样' },
  { file: '07-fillet-chamfer.json', label: '示例7 倒圆与倒角' },
  { file: '08-analysis-pack.json', label: '示例8 几何分析' },
  { file: '09-vector-math.json', label: '示例9 向量与数学' },
  { file: '10-list-pipeline.json', label: '示例10 列表管线' },
  { file: '11-mirror-array.json', label: '示例11 镜像与线阵' },
  { file: '12-expression-drive.json', label: '示例12 表达式驱动' },
  { file: '13-primitives-gallery.json', label: '示例13 基础实体画廊' },
  { file: '14-cone-torus-union.json', label: '示例14 圆锥与圆环并集' },
  { file: '15-shell-offset-stack.json', label: '示例15 偏移叠层' },
  { file: '16-grid-city.json', label: '示例16 网格阵列城市' },
  { file: '17-polar-crown.json', label: '示例17 极坐标冠环' },
  { file: '18-loft-twist.json', label: '示例18 放样扭转' },
  { file: '19-math-driven-radius.json', label: '示例19 数学驱动半径' },
  { file: '20-analysis-dashboard.json', label: '示例20 分析仪表盘' },
  { file: '21-flange-ring.json', label: '示例21 法兰盘' },
  { file: '22-bolt-simple.json', label: '示例22 螺栓' },
  { file: '23-nut-simple.json', label: '示例23 螺母' },
  { file: '24-door-frame.json', label: '示例24 门框与门板' },
  { file: '25-i-beam-section.json', label: '示例25 工字钢截面' },
  { file: '26-c-channel-section.json', label: '示例26 槽钢截面' },
  { file: '27-angle-steel-section.json', label: '示例27 角钢截面' },
  { file: '28-tube-column-base.json', label: '示例28 方管立柱底座' },
  { file: '29-bracket-l-shape.json', label: '示例29 L型支架' },
  { file: '30-plate-with-holes.json', label: '示例30 多孔板' },
  { file: '31-pipe-flange-joint.json', label: '示例31 管道法兰连接' },
  { file: '32-bolt-nut-assembly.json', label: '示例32 螺栓螺母组合' },
  { file: '33-hinged-door-set.json', label: '示例33 铰链门组件' },
  { file: '34-window-frame-set.json', label: '示例34 窗框组件' },
  { file: '35-h-beam-column-joint.json', label: '示例35 H型钢柱节点' },
  { file: '36-truss-node-plate.json', label: '示例36 桁架节点板' },
  { file: '37-base-plate-anchor.json', label: '示例37 底板锚栓节点' },
  { file: '38-stiffener-bracket.json', label: '示例38 加劲板支座' },
  { file: '39-machine-foot.json', label: '示例39 设备底脚' },
  { file: '40-guardrail-post.json', label: '示例40 护栏立柱' },
  { file: '41-pipe-elbow-flange-set.json', label: '示例41 管道弯头法兰组' },
  { file: '42-column-base-anchor-frame.json', label: '示例42 柱脚锚栓框架' },
  { file: '43-steel-column-beam-node.json', label: '示例43 钢柱梁连接节点' },
  { file: '44-truss-gusset-node.json', label: '示例44 桁架连接板节点' },
  { file: '45-machine-skid-foot.json', label: '示例45 设备滑橇底座' },
  { file: '46-stiffener-rib-bracket.json', label: '示例46 加劲肋支架' },
  { file: '47-motor-mount-plate.json', label: '示例47 电机安装板' },
  { file: '48-valve-flange-body.json', label: '示例48 阀体法兰组合' },
  { file: '49-window-mullion-frame.json', label: '示例49 窗挺框组合' },
  { file: '50-double-door-frame-set.json', label: '示例50 双扇门框组' },
  { file: '51-square-tube-column-base.json', label: '示例51 方管柱脚底座' },
  { file: '52-angle-bracket-pair.json', label: '示例52 角码支架组' },
  { file: '53-bolt-washer-nut-set.json', label: '示例53 螺栓垫片螺母组' },
  { file: '54-door-head-jamb-set.json', label: '示例54 门楣与门框组' },
  { file: '55-guardrail-post-baseplate.json', label: '示例55 护栏柱底板节点' },
];
